### PR TITLE
support setting the C++ standard

### PR DESCRIPTION
**Pull request by jll63**

### CODE REVIEW

**Comment by jll63** [comment]
Can you take a look please? In particular at the `cmake` changes.

**Comment by derpda** [comment]
I'm traveling for another 10 days at least, I'll get on it when I'm back!

**Comment by jll63** [comment]
I hope you are enjoying your trip.
I had to reshuffle branches and I accidentally merged and closed this PR. But it's still worth you taking a look...

**Comment by derpda** [comment]
I'm back now and had a look at the changes. The cmake changes look good to me!

**Pull request merged**
